export enum ReportReason {
    SPAM = "SPAM",
    HARASSMENT = "HARASSMENT",
    SEXUAL_CONTENT = "SEXUAL_CONTENT",
    HATE_SPEECH = "HATE_SPEECH",
    DISCRIMINATION = "DISCRIMINATION",
    OTHER = "OTHER",
}